compute:
  chunk_size: 10000
  memory_limit_gb: 8
  n_jobs: -1
  use_polars: true
cross_validation:
  holdout_test: false
  min_train_days: 7.0
  n_folds: 3
  purge_gap_minutes: 10
  segment_isolation: false
  test_span_days: 3.0
  time_based_split: true
  val_span_days: 3.0
data_storage:
  compression: snappy
  format: pickle
  output_directory: Data/prepared
  segments_meta_file: segments_meta.csv
  version_control: true
evaluation:
  event_level_evaluation: true
  metrics:
  - pr_auc
  - f1
  - f0.5
  - f2
  - recall_at_k
  - precision
  - recall
  per_device_evaluation: true
  probability_calibration: true
  threshold_tuning: true
  visualization:
    dpi: 300
    enabled: true
    plots:
    - confusion_matrix
    - roc_curve
    - pr_curve
    - calibration_curve
    - prediction_timeline
    save_format: png
feature_engineering:
  derived_features:
    cross_correlations: false
    interaction_terms: false
    polynomial_features: false
    power_ratios: true
  feature_selection:
    enabled: true
    k_best: 30
    method: mutual_info
    variance_threshold: 0.01
  normalization:
    enabled: true
    method: robust
    per_device: true
    per_segment: false
  statistical_features:
    change_rate: true
    energy_integral: true
    harmonic_ratios: true
    rolling_mean:
    - 5
    - 10
    - 20
    rolling_min_max:
    - 10
    - 20
    rolling_std:
    - 5
    - 10
    - 20
  time_features:
    day_of_week: true
    hour_of_day: true
    is_holiday: false
    is_weekend: true
frequency:
  hop_length: 64
  magnitude: true
  n_fft: 256
  signal: P_kW
  win_length: 256
hipe:
  device_cols:
    P: P_kW
    Q: Q_kvar
    S: S_kVA
  device_pattern: '*_PhaseCount_*.csv'
  enable: true
  label_mode: regression
  mains_cols:
    PF: L_F
    P_kW: P_kW
    Q_kvar: Q_kvar
    S_kVA: S_kVA
  mains_file: MainTerminal*_PhaseCount_*.csv
  on_power_threshold_w: 0.5
  on_ratio_threshold: 0.5
  resample_seconds: 5
  step_size: 128
  stft:
    hop_length: 64
    n_fft: 256
    win_length: 256
    window: hann
  timestamp_col: datetime
  window_length: 256
imbalance_handling:
  class_weight_auto: true
  focal_loss_gamma: 2.0
  loss_weighting: true
  sampling_strategy: mixed
  segment_sampling_weight: 2.0
  window_sampling_ratio: 0.3
labels:
  event_definitions:
  - direction: up
    event_type: power_on
    feature_column: power
    max_gap: 3
    min_duration: 5
    threshold: 100.0
  - direction: down
    event_type: power_off
    feature_column: power
    max_gap: 3
    min_duration: 5
    threshold: 50.0
  - direction: both
    event_type: state_change
    feature_column: switch_state
    max_gap: 1
    min_duration: 1
    threshold: 0.5
  event_detection_threshold: 0.1
  imbalance_handling:
    enabled: true
    strategy: mixed
    target_ratio: 0.3
  label_config:
    aggregation: any
    causality_check: true
    horizon: 3
    label_type: binary
  onoff:
    enabled: true
    feature_column: P_kW
    hysteresis_margin: 0.1
    method: absolute
    min_off_duration: 5
    min_on_duration: 5
    off_threshold: 0.3
    on_ratio_threshold: 0.5
    on_threshold: 0.5
    per_device:
      ChipPress:
        hysteresis_margin: 1.0e-06
        mad: 1.0e-06
        median_window: 5
        method: absolute
        min_off_duration: 67
        min_on_duration: 67
        off_threshold: 12.079921
        on_threshold: 12.079923
        smooth_window: 9
      ChipSaw:
        hysteresis_margin: 1.0e-06
        mad: 1.0e-06
        median_window: 5
        method: absolute
        min_off_duration: 96
        min_on_duration: 96
        off_threshold: 0.010663
        on_threshold: 0.010665
        smooth_window: 9
      HighTemperatureOven:
        hysteresis_margin: 1.0e-06
        mad: 1.0e-06
        median_window: 3
        method: absolute
        min_off_duration: 96
        min_on_duration: 96
        off_threshold: 2.008029
        on_threshold: 2.00803
        smooth_window: 5
      PickAndPlaceUnit:
        hysteresis_margin: 1.0e-06
        mad: 1.0e-06
        median_window: 5
        method: absolute
        min_off_duration: 96
        min_on_duration: 96
        off_threshold: -0.002384
        on_threshold: -0.002382
        smooth_window: 9
      ScreenPrinter:
        hysteresis_margin: 1.0e-06
        mad: 1.0e-06
        median_window: 5
        method: absolute
        min_off_duration: 96
        min_on_duration: 96
        off_threshold: 0.009873
        on_threshold: 0.009875
        smooth_window: 9
      SolderingOven:
        hysteresis_margin: 1.0e-06
        mad: 1.0e-06
        median_window: 3
        method: absolute
        min_off_duration: 96
        min_on_duration: 96
        off_threshold: 2.709596
        on_threshold: 2.709597
        smooth_window: 5
      VacuumOven:
        hysteresis_margin: 1.0e-06
        mad: 1.0e-06
        median_window: 3
        method: absolute
        min_off_duration: 59
        min_on_duration: 59
        off_threshold: 0.720182
        on_threshold: 0.720183
        smooth_window: 5
      VacuumPump1:
        hysteresis_margin: 1.0e-06
        mad: 1.0e-06
        median_window: 5
        method: absolute
        min_off_duration: 96
        min_on_duration: 96
        off_threshold: 0.012577
        on_threshold: 0.012579
        smooth_window: 9
      VacuumPump2:
        hysteresis_margin: 1.0e-06
        mad: 1.0e-06
        median_window: 3
        method: absolute
        min_off_duration: 96
        min_on_duration: 96
        off_threshold: 0.017274
        on_threshold: 0.017275
        smooth_window: 5
      WashingMachine:
        delta_k: 3.0
        delta_threshold: 3.0e-06
        mad_diff: 1.0e-06
        median_window: 3
        method: delta
        min_off_duration: 96
        min_on_duration: 96
        smooth_window: 5
    smooth_window: 3
  sampling_strategy: mixed
logging:
  console: true
  file: logs/data_prep.log
  level: INFO
random:
  deterministic: true
  seed: 42
segmentation:
  fill_method: forward
  fill_small_gaps: true
  gap_threshold_seconds: 300
  max_segment_hours: 24
  min_segment_length: 100
  small_gap_threshold: 30
windowing:
  default_step_size: 128
  default_window_length: 256
  max_filled_ratio: 0.3
  max_windows_per_segment: 500
  overlap_across_sets: false
  overlap_within_set: true
  step_sizes:
  - 128
  window_lengths:
  - 256
