# DisaggNet 默认配置
# 继承基础配置，适用于快速实验和开发

defaults:
  - base

experiment:
  name: "baseline"

logging:
  version: "v1"

# 损失设置（统一损失函数配置）
loss:
  # 多任务损失权重 (推荐配置: 2*L_cls + 1*L_reg + 0.5*L_conservation + 1*L_consistency)
  classification_weight: 2.0    # 分类损失权重
  regression_weight: 1.0        # 回归损失权重  
  conservation_weight: 0.5      # 能量守恒损失权重
  consistency_weight: 1.0       # 一致性损失权重
  
  # Focal Loss参数
  focal_alpha: 0.25            # Focal Loss alpha参数
  focal_gamma: 2.0             # Focal Loss gamma参数
  
  # Huber Loss参数
  huber_delta: 1.0             # Huber Loss delta参数

# 评估与策略（见文件末尾统一定义）

# 模型配置
model:
  freq_encoder:
    enable: true
  fusion:
    type: "cross_attention"
  # 多任务头配置
  heads:
    classification:
      # 分类头初始化先验概率 (将在训练时自动注入数据统计先验)
      init_p: null  # 自动从数据统计计算
    regression:
      # 回归头配置
      dropout: 0.1
  
  # 校准配置
  calibration:
    enable: true
    temperature_init: 1.0

# 训练策略配置
training:
  max_epochs: 100
  patience: 15
  min_delta: 0.001
  
  # 学习率调度
  lr_scheduler:
    name: "cosine"
    warmup_epochs: 5
    eta_min: 1e-6
  
  # 优化器配置
  optimizer:
    name: "adamw"
    lr: 1e-3
  masking:
    window_strategy: "none"
    min_valid_ratio_time: 0.5
    min_valid_ratio_freq: 0.5
    combine_modalities: "min"
    downweight_power: 1.0
    epsilon: 0.0
  
  # 事件关注配置（用于训练期提升含事件样本的权重）
  event_focus:
    enable: true
    weight: 2.0
  
  # 训练期可视化设置（仅绘制含事件窗口以便快速对齐）
  visualization:
    plot_event_only: true
    max_plots_per_epoch: 16

# 不平衡处理（数据模块读取）
imbalance_handling:
  sampling_strategy: "mixed"

# Walk-Forward 交叉验证（与 walk_forward.py 对齐）
walk_forward:
  n_folds: 3
  purge_gap_minutes: 10
  val_span_days: 3.0
  test_span_days: 3.0
  min_train_days: 7.0
  segment_isolation: false
  holdout_test: true
  time_based_split: true

# 数据准备设置（基础版本）
data_preparation:
  window_size: 256
  stride: 128
  feature_engineering:
    enable_advanced: false
    statistical_windows: [6, 12, 24]

# 稳定性设置（基础版本）
stability:
  numerical:
    detect_anomaly: false
    gradient_clip_val: 0.5
  reproducibility:
    deterministic: false
    benchmark: true

# 保留的配置项（避免重复）
conformal_prediction:
  enable: false
  alpha: 0.1
  regression_method: "quantile"
  classification_method: "logits"

# 复现实验设置（供 main.py 使用）
reproducibility:
  seed: 42
  deterministic: false
  benchmark: true

# 评估与策略
evaluation:
  threshold_method: "optimal"
  # 降低全零窗口在指标计算中的权重（0~1）
  zero_window_weight: 0.2