# DisaggNet 稳定优化配置
# 继承基础配置，针对稳定性和性能进行优化

defaults:
  - base

experiment:
  name: "optimized_stable"

logging:
  version: "stable"

# 优化的数据设置
data:
  batch_size: 512
  num_workers: 8

# 优化的模型设置
model:
  num_layers: 8
  dropout: 0.2
  calibration:
    enable: true

# 优化的训练设置
training:
  max_epochs: 100
  optimizer:
    lr: 0.0005
  scheduler:
    warmup_steps: 1000
    T_max: 200

# 损失设置（优化版本）
loss:
  weights:
    regression: 1.0
    classification: 1.0
    consistency_schedule:
      start_epoch: 5
      end_epoch: 40
      min_weight: 0.0
      max_weight: 0.6
  device_weights:
    enable: false
  classification:
    focal:
      enable: true
      gamma: 2.0
      alpha: 1.0

# 评估设置
evaluation:
  threshold_method: "optimal"

# 不平衡处理
imbalance_handling:
  sampling_strategy: "mixed"

# Walk-Forward 交叉验证（优化版本）
walk_forward:
  n_folds: 5
  purge_gap_minutes: 15
  val_span_days: 5.0
  test_span_days: 5.0
  min_train_days: 10.0
  segment_isolation: true
  holdout_test: true
  time_based_split: true

# 稳定性设置
stability:
  numerical:
    detect_anomaly: true
    gradient_clip_val: 1.0
  reproducibility:
    deterministic: true
    benchmark: false

# 数据准备设置（优化版本）
data_preparation:
  window_size: 1024
  stride: 512
  feature_engineering:
    enable_advanced: true
    statistical_windows: [12, 24, 48]

# 复现实验设置（供 main.py 使用）
reproducibility:
  seed: 42
  deterministic: true
  benchmark: false