# Windows优化的训练配置
# 针对Windows系统的PyTorch Lightning训练性能优化

project_name: "DisaggNet"

experiment:
  name: "windows_optimized"

reproducibility:
  seed: 42
  deterministic: false
  benchmark: true

paths:
  output_dir: "outputs"
  data_dir: "Data"
  prepared_dir: "Data/prepared"

logging:
  save_dir: "logs/tensorboard"
  version: "v1"

data:
  batch_size: 64  # 适中的批次大小，平衡内存和性能
  num_workers: 4  # Windows下使用较少的worker
  pin_memory: true  # Windows下启用pin_memory提升GPU传输
  persistent_workers: true  # 减少worker重启开销
  prefetch_factor: 1  # 减少内存占用
  window_size: 256
  cv:
    fold_id: 0

model:
  d_model: 256
  n_heads: 8
  num_layers: 4  # 减少层数提升速度
  dropout: 0.1
  calibration:
    enable: false  # 禁用校准减少计算
  time_encoder:
    d_model: 256
    n_heads: 8
    num_layers: 4
    dropout: 0.1
    input_conv_embed: false
    causal_mask: true
  freq_encoder:
    enable: false  # 禁用频域编码器提升速度
    proj_dim: 128
    conv1d_kernel: 3
    small_transformer_layers: 0
    dropout: 0.1
  fusion:
    type: "cross_attention"
    gated: true
  aux_encoder:
    enable: true
    hidden: 128
    dropout: 0.1
  heads:
    regression:
      hidden: 96
      dropout: 0.1
    classification:
      init_p: null

training:
  max_epochs: 50  # 减少epoch数用于快速测试
  min_epochs: 1
  precision: "16-mixed"  # 使用混合精度提升速度
  log_every_n_steps: 50  # 减少日志频率
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 2  # 减少验证频率
  accelerator: "auto"
  devices: 1  # 单GPU训练
  monitor_device_stats: false  # 禁用设备监控减少开销
  
  # Windows优化设置
  visualization:
    enable: false  # 禁用可视化避免阻塞
    plot_event_only: true
    max_plots_per_epoch: 0
  
  # 事件聚焦设置
  event_focus:
    enable: true
    weight: 2.0
  
  # 窗口屏蔽设置（简化）
  masking:
    window_strategy: "none"  # 禁用复杂的窗口屏蔽
  
  optimizer:
    name: "adamw"
    lr: 0.002  # 稍高的学习率加速收敛
    weight_decay: 0.01
    betas: [0.9, 0.999]
  
  scheduler:
    name: "cosine"
    warmup_steps: 200  # 减少warmup步数
    T_max: 50
    eta_min: 1e-6
  
  checkpoint:
    dirpath: "outputs/checkpoints"
    filename: "epoch={epoch:02d}-val_score={val/score:.4f}"
    monitor: "val/score"
    mode: "max"
    save_top_k: 1
    save_last: false  # 不保存最后一个checkpoint
  
  early_stopping:
    enable: true
    monitor: "val/score"
    patience: 10  # 减少patience加速训练

# 损失函数配置（简化）
loss:
  classification_weight: 0.0  # 禁用分类损失专注回归
  regression_weight: 1.0
  conservation_weight: 0.1  # 减少守恒损失权重
  consistency_weight: 0.1   # 减少一致性损失权重

# 评估配置
evaluation:
  threshold_method: "fixed"  # 使用固定阈值避免动态计算
  fixed_threshold: 0.5
  zero_window_weight: 0.5

# 调试配置
debug:
  track_grad_norm: 0  # 禁用梯度范数跟踪
  validate_inputs: false  # 禁用输入验证
  log_memory_usage: false  # 禁用内存使用日志

# 辅助训练配置（禁用复杂功能）
aux_training:
  metric_learning:
    enable: false  # 禁用度量学习
  
# 共形预测配置（禁用）
conformal_prediction:
  enable: false

# Hydra配置
defaults:
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  launcher:
    _target_: hydra._internal.BasicLauncher
  sweeper:
    _target_: hydra._internal.BasicSweeper
    max_jobs: 1
  help:
    app_name: ${hydra:job.name}
    header: '${hydra:help.app_name} is powered by Hydra.

    '
    footer: 'Powered by Hydra (https://hydra.cc)
    Use --hydra-help to view Hydra specific help

    '
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [console]
    loggers:
      hydra:
        level: INFO
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra:runtime.output_dir}/${hydra:job.name}.log
    root:
      level: INFO
      handlers: [console, file]
    disable_existing_loggers: false